Ben/powerup
Frinksy/PixelBoat pull request #15
Opened 2021-02-06 21:36 UTC by UnwiseCheese98

Pull request checklist:
- [ ] Merge conflicts have been resolved
- [ ] The UML diagrams have been updated accordingly
- [ ] My changes respect the Google Java Style

2021-02-06 21:43 UTC, UnwiseCheese98 commented
[changestouml2.txt](https://github.com/Frinksy/PixelBoat/files/5937727/changestouml2.txt)

2021-02-07 12:31 UTC, Frinksy commented on Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/Boat.java
> +   *
there's an extra space on that line that causes checkstyle to fail

2021-02-07 12:37 UTC, Frinksy requested changes
There's more, log of errors is:
```
2021-02-06T21:37:13.8902768Z [ant:checkstyle] [ERROR] /home/runner/work/PixelBoat/PixelBoat/Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/Boat.java:130: Javadoc tag '@author' should be preceded with an empty line. [RequireEmptyLineBeforeBlockTagGroup]
2021-02-06T21:37:13.8903935Z 
2021-02-06T21:37:13.8906794Z [ant:checkstyle] [ERROR] /home/runner/work/PixelBoat/PixelBoat/Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/Boat.java:143: Javadoc tag '@author' should be preceded with an empty line. [RequireEmptyLineBeforeBlockTagGroup]
2021-02-06T21:37:13.8908070Z > Task :core:checkstyleMain
2021-02-06T21:37:13.8909968Z [ant:checkstyle] [ERROR] /home/runner/work/PixelBoat/PixelBoat/Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/Boat.java:156: Javadoc tag '@author' should be preceded with an empty line. [RequireEmptyLineBeforeBlockTagGroup]
2021-02-06T21:37:13.8912465Z [ant:checkstyle] [ERROR] /home/runner/work/PixelBoat/PixelBoat/Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/Boat.java:169: Javadoc tag '@author' should be preceded with an empty line. [RequireEmptyLineBeforeBlockTagGroup]
2021-02-06T21:37:13.8914476Z [ant:checkstyle] [ERROR] /home/runner/work/PixelBoat/PixelBoat/Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/PowerUpDrag.java:6: First sentence of Javadoc is missing an ending period. [SummaryJavadoc]
2021-02-06T21:37:13.8916278Z [ant:checkstyle] [ERROR] /home/runner/work/PixelBoat/PixelBoat/Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/PowerUpEnergy.java:6: First sentence of Javadoc is missing an ending period. [SummaryJavadoc]
2021-02-06T21:37:13.8918173Z [ant:checkstyle] [ERROR] /home/runner/work/PixelBoat/PixelBoat/Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/PowerUpHealth.java:6: First sentence of Javadoc is missing an ending period. [SummaryJavadoc]
2021-02-06T21:37:13.8929884Z [ant:checkstyle] [ERROR] /home/runner/work/PixelBoat/PixelBoat/Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/PowerUpHealth.java:26:4: Block comment has incorrect indentation level 3, expected is 2, indentation should be the same level as line 35. [CommentsIndentation]
2021-02-06T21:37:13.8932328Z [ant:checkstyle] [ERROR] /home/runner/work/PixelBoat/PixelBoat/Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/PowerUpRotation.java:6: First sentence of Javadoc is missing an ending period. [SummaryJavadoc]
2021-02-06T21:37:13.8934388Z [ant:checkstyle] [ERROR] /home/runner/work/PixelBoat/PixelBoat/Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/PowerUpRotation.java:26:4: Block comment has incorrect indentation level 3, expected is 2, indentation should be the same level as line 35. [CommentsIndentation]
2021-02-06T21:37:13.8936442Z [ant:checkstyle] [ERROR] /home/runner/work/PixelBoat/PixelBoat/Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/PowerUpSpeed.java:6: First sentence of Javadoc is missing an ending period. [SummaryJavadoc]
2021-02-06T21:37:13.8938445Z [ant:checkstyle] [ERROR] /home/runner/work/PixelBoat/PixelBoat/Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/PowerUpSpeed.java:26:4: Block comment has incorrect indentation level 3, expected is 2, indentation should be the same level as line 35. [CommentsIndentation]
```

Test with `./gradlew checkstyleMain`

2021-02-07 12:37 UTC, Frinksy commented on Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/Boat.java
> +   *
there's an extra space on that line that causes checkstyle to fail

2021-02-07 12:37 UTC, Frinksy commented on Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/Boat.java
> +   *
there's an extra space on that line that causes checkstyle to fail

2021-02-07 12:37 UTC, Frinksy commented on Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/Boat.java
> +   *
there's an extra space on that line that causes checkstyle to fail

2021-02-07 12:37 UTC, Frinksy commented on Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/Boat.java
> +   *
there's an extra space on that line that causes checkstyle to fail

2021-02-07 12:37 UTC, Frinksy commented on Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/PowerUpDrag.java
> + * Represents the drag reduction power up
needs full stop

2021-02-07 12:37 UTC, Frinksy commented on Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/PowerUpEnergy.java
> + * Represents the Energy power up
needs a full stop

2021-02-07 12:37 UTC, Frinksy commented on Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/PowerUpHealth.java
> + * Represents the Health power up
needs a full stop

2021-02-07 12:37 UTC, Frinksy commented on Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/PowerUpHealth.java
>     */
Block comment has incorrect indentation level 3, expected is 2,

2021-02-07 12:37 UTC, Frinksy commented on Implementation/core/src/main/java/com/teamonehundred/pixelboat/entities/PowerUpRotation.java
> + * Represents the rotation power up
needs a full stop

2021-02-07 17:42 UTC, closed without merging